config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'e_scooters#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :e_scooters do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, except: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :e_scooter
end

app/models/e_scooter.rb
class EScooter < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

# IMAGES =
# ["https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759717/snhq59gta3s26jkb69ly.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759869/nvcqu0kk3mcnjdtutxr7.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759820/oyn12omhokhjl6bcdnee.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759765/xajylskwf3ajmruyuzeu.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759672/qkh8fabexb0l3th6a3m3.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759615/gp2issa1bf0ru5nt4ldo.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759559/jkp3uk60je426m6qzin7.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759508/w3egrtlhk3eii91quyem.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759276/wilppmejawgwhstc0swr.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648759187/usbdtqlizt4jyvorso8f.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648757891/xrivrikxxpxseahxvn6f.jpg",
#   "https://res.cloudinary.com/dqbqhn0zw/image/upload/v1648757783/yjqslynyoahtkso8ntr3.jpg"
# ]

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :e_scooters
  has_many :bookings
  has_many :e_scooters, through: :bookings


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:owner])
    devise_parameter_sanitizer.permit(:account_update, keys: [:owner])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy, :show]
  before_action :set_e_scooter, only: [:new, :create]

  def index
    if current_user.owner == true
      e_scooter = EScooter.where(user_id: current_user)
      @bookings = Booking.where(e_scooter_id: e_scooter)
    else
      @bookings = Booking.where(user_id: current_user.id)
    end
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.e_scooter = @e_scooter
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @e_scooter = EScooter.find(@booking.e_scooter_id)
    @booking.destroy
    redirect_to e_scooter_path(@e_scooter)
  end

  private

  def set_e_scooter
    @e_scooter = EScooter.find(params[:e_scooter_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date)
  end
end

app/controllers/e_scooters_controller.rb
class EScootersController < ApplicationController
  before_action :set_e_scooter, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if user_signed_in? && current_user.owner == true
      @e_scooters = EScooter.where(user_id: current_user.id)
    else
      @e_scooters = EScooter.all
    end
  end

  def show
    @e_scooter = EScooter.find(params[:id])
  end

  def new
    @e_scooter = EScooter.new
  end

  def create
    @e_scooter = EScooter.new(e_scooter_params)
    @e_scooter.user = current_user
    if @e_scooter.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @e_scooter.update(e_scooter_params)
    redirect_to e_scooters_path
  end

  def destroy
    @e_scooter.destroy
    redirect_to root_path
  end

  private

  def set_e_scooter
    @e_scooter = EScooter.find(params[:id])
  end

  def e_scooter_params
    params.require(:e_scooter).permit(:name, :description, :price, :street_name, :disponibility_start, :disponibility_end, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1> Your bookings </h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @bookings.each do |booking| %>
    <div class="col-sm-4">
      <div class="card">
        <%= cl_image_tag booking.e_scooter.photo.key, crop: :fill %>
        <div class="card-body">
          <h5 class="card-title fw-bold"><%= link_to booking.e_scooter.name, booking_path(booking), class: "text-decoration-none" %></h5>
          <p class="card-text">From <%= booking.check_in_date %></p>
          <p class="card-text">Until <%= booking.check_out_date %></p>
          <p class="card-text">Price : <%= booking.e_scooter.price %>€/day </p>
          <% start_time =  booking.check_in_date %>
          <% end_time   =  booking.check_out_date%>
          <p>Total : <strong><%= (end_time - start_time).to_i * booking.e_scooter.price%>€</strong> </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
 <a href="/e_scooters" class="btn btn-secondary btn active mb-3" role="button" aria-pressed="true">Homepage</a>
</div>

app/views/bookings/new.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>Book a E-scooter</h1>
  </div>
</div>


<div class="container">
  <%= simple_form_for [@e_scooter, @booking] do |f| %>
    <%= f.input :check_in_date %>
    <%= f.input :check_out_date %>
    <%= f.submit class: 'btn btn-secondary mt-3' %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>Your booking</h1>
  </div>
</div>

<div class="container mt-3">
  <div class="card-product" class="d-flex justify-content-center">
    <div class="d-flex">
      <%= cl_image_tag @booking.e_scooter.photo.key,  height: 400, width: 355, crop: :fill %>
    <div class="card-infos " >
      <h2><%= @booking.e_scooter.name %></h2>
      <h3>Réservation</h3>
      <h4>from : <%= @booking.check_in_date %></h4>
      <h4>to : <%= @booking.check_out_date %></h4>
      <% start_time =  @booking.check_in_date %>
      <% end_time   =  @booking.check_out_date%>
      <p><%= distance_of_time_in_words(start_time, end_time)%> at <%= @booking.e_scooter.price %>€/day </p>
      <p>Total of <strong><%= (end_time - start_time).to_i * @booking.e_scooter.price%>€</strong> </p>
    </div>
    </div>
  </div>
  <div class="d-flex justify-content-around">
    <div>
      <p><%= link_to "See all your bookings", bookings_path, class: "btn btn-secondary mt-3" %></p>
      <p><%= link_to "Back to e_scooters list", e_scooters_path, class: "btn btn-secondary mt-3" %></p>
      <p><%= link_to "Delete this booking",
                  booking_path(@booking),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-secondary mt-3" %></p>
    </div>
    <img class="gif" src="https://c.tenor.com/zRfxxnlRTK0AAAAC/thats-how-i-roll-chihuahua.gif" alt="Card image cap">
  </div>
</div>

app/views/e_scooters/edit.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>Edit E-scooter</h1>
  </div>
</div>




<div class="container">
  <%= simple_form_for @e_scooter do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :street_name %>
    <%= f.input :disponibility_start %>
    <%= f.input :disponibility_end %>
    <%= f.submit "Update your e-scooter", class: "btn btn-secondary mb-3" %>
  <% end %>
</div>

app/views/e_scooters/index.html.erb
<div class="banner-index-e_scooters" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(240,240,240,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h2>Welcome to</h2>
    <h1>TROC TO TROT 836</h1>
    <p>Choose it, Book  it and Ride it !</p>
  </div>
</div>

<div class="container">
  <div class="row">
      <% @e_scooters.each do |e_scooter| %>
      <div class="col-sm-4">
        <div class="card cover">
        <%= cl_image_tag e_scooter.photo.key, crop: :fill %>
          <div class="card-body">
            <h5 class="card-title fw-bold"><%= link_to e_scooter.name, e_scooter_path(e_scooter), class: "text-decoration-none" %></h5>
            <p class="card-text"><%= e_scooter.price %>€/jour </p>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <div class="btn-index" >
      <p><% if user_signed_in? && current_user.owner == true %>
        <a href="/e_scooters/new" class="btn btn-secondary btn active" role="button" aria-pressed="true">Create</a>
        <a href="/bookings" class="btn btn-secondary btn active" role="button" aria-pressed="true">Your Bookings</a>
      <% end %></p>

      <%# <p><% if user_signed_in? && current_user.owner == false %>
        <%# <a href="/bookings" class="btn btn-secondary btn active" role="button" aria-pressed="true">Your Bookings</a> %>
      <%# <% end %>
    </div>
  </div>
</div>

app/views/e_scooters/new.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>New E-Scooter </h1>
  </div>
</div>

<div class="container mt-3">
  <%= simple_form_for @e_scooter do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :street_name %>
    <%= f.input :disponibility_start %>
    <%= f.input :disponibility_end %>
    <%= f.submit "Create new e-scooter", class: "btn btn-secondary" %>
<% end %>
<%= link_to 'Homepage', root_path, class: "btn btn-secondary mt-3 mb-3" %>

</div>

app/views/e_scooters/show.html.erb
<div class="banners" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1566936737687-8f392a237b8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80);">
  <div class="container">
    <h1>Your E-scooter</h1>
  </div>
</div>

<div class="container mt-3">
  <div class="card-product" class="d-flex justify-content-center">
    <div class="d-flex">
      <%= cl_image_tag @e_scooter.photo.key, height: 400, width: 355, crop: :fill %>
      <div class="card-infos " >
        <h2><%= @e_scooter.name %></h2>
        <p><%= @e_scooter.description %></p>
        <p><%= @e_scooter.price %>€/jour</p>
        <p><%= @e_scooter.street_name %></p>
        <p><%= @e_scooter.disponibility_start %></p>
        <p><%= @e_scooter.disponibility_end %></p>
      </div>
    </div>
    <p><% if user_signed_in? && current_user.owner == true %>

    <p><%= link_to "Edit this e_scooter", edit_e_scooter_path(@e_scooter), class: "btn btn-secondary mt-3" %></p>
    <p><%= link_to "Delete #{@e_scooter.name}",
                  e_scooter_path(@e_scooter),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: "btn btn-secondary mt-3" %></p>
    <% end %></p>
    <p><% if user_signed_in? && current_user.owner == false %>
      <p><%= link_to "Book this e_scooters", new_e_scooter_booking_path(@e_scooter), class: "btn btn-secondary mt-3" %></p>
    <% end %></p>
    <p><%= link_to "Back to e_scooters list", e_scooters_path, class: "btn btn-secondary mt-3 mb-3" %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TROCDeTrot836</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%# <%= render 'shared/flashes' %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to 'delete', destroy_user_session_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-copyright">
  This footer is made with ' <i class="fas fa-heart"></i> ' by ©Troc-to-Trot
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="logo_img">
      <%= link_to "/e_scooters", class: "navbar-brand" do %>
        <%= image_tag "escooter_logo.png", alt: "alttext", class: "logo"%>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Your bookings", "/bookings", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", "/e_scooters", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", alt: "alttext", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>